services:
  mysql:
    image: mysql:8.0
    container_name: iptv-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: iptv_root_password
      MYSQL_DATABASE: iptv_manager
      MYSQL_USER: iptv_user
      MYSQL_PASSWORD: iptv_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - iptv-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "iptv_user", "-piptv_password"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: iptv-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: iptv_root_password
      MYSQL_ROOT_PASSWORD: iptv_root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - iptv-network

  app:
    build: .
    container_name: iptv-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=iptv_user
      - DB_PASSWORD=iptv_password
      - DB_NAME=iptv_manager
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-change-in-production
      - API_URL=http://localhost:3001
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - iptv-network
    command: sh -c "npm run dev:api:wait & sleep 5 && npm run dev:next && wait"

volumes:
  mysql_data:

networks:
  iptv-network:
    driver: bridge